usr/bin/ark
usr/lib/kde4/kerfuffle_bk.so
usr/lib/kde4/kerfuffle_libzip.so
usr/lib/kde4/libarkpart.so
usr/lib/libkerfuffle.so.4
usr/lib/libkerfuffle.so.4.0.0
usr/share/applications/kde4/ark.desktop
usr/share/kde4/apps/ark/ark_part.rc
usr/share/kde4/apps/ark/arkui.rc
usr/share/kde4/config.kcfg/ark.kcfg
usr/share/kde4/services/ark_part.desktop
usr/share/kde4/services/kerfuffle_bk.desktop
usr/share/kde4/services/kerfuffle_libzip.desktop
usr/share/kde4/servicetypes/kerfufflePlugin.desktop

