usr/share/doc/kde4/HTML/en/ark/index.cache.bz2
usr/share/doc/kde4/HTML/en/ark/index.docbook
usr/share/doc/kde4/HTML/en/ark/man-ark.1.docbook

usr/share/doc/kde4/HTML/en/kcalc/index.cache.bz2
usr/share/doc/kde4/HTML/en/kcalc/index.docbook
usr/share/doc/kde4/HTML/en/kcalc/commands.docbook

usr/share/doc/kde4/HTML/en/kcharselect/index.cache.bz2
usr/share/doc/kde4/HTML/en/kcharselect/index.docbook

usr/share/doc/kde4/HTML/en/kdf/index.cache.bz2
usr/share/doc/kde4/HTML/en/kdf/index.docbook
usr/share/doc/kde4/HTML/en/kdf/kdf_config.png
usr/share/doc/kde4/HTML/en/kdf/kdf.png

usr/share/doc/kde4/HTML/en/kfloppy/index.cache.bz2
usr/share/doc/kde4/HTML/en/kfloppy/index.docbook

usr/share/doc/kde4/HTML/en/kgpg/index.cache.bz2
usr/share/doc/kde4/HTML/en/kgpg/index.docbook
usr/share/doc/kde4/HTML/en/kgpg/editor.png
usr/share/doc/kde4/HTML/en/kgpg/keygen.png
usr/share/doc/kde4/HTML/en/kgpg/keymanage.png
usr/share/doc/kde4/HTML/en/kgpg/keyprop.png
usr/share/doc/kde4/HTML/en/kgpg/keys.png
usr/share/doc/kde4/HTML/en/kgpg/keyserver.png
usr/share/doc/kde4/HTML/en/kgpg/kicker.png
usr/share/doc/kde4/HTML/en/kgpg/options.png

usr/share/doc/kde4/HTML/en/khexedit/index.cache.bz2
usr/share/doc/kde4/HTML/en/khexedit/index.docbook
usr/share/doc/kde4/HTML/en/khexedit/khexedit1.png

usr/share/doc/kde4/HTML/en/kjots/index.cache.bz2
usr/share/doc/kde4/HTML/en/kjots/index.docbook

usr/share/doc/kde4/HTML/en/KRegExpEditor/index.cache.bz2
usr/share/doc/kde4/HTML/en/KRegExpEditor/index.docbook
usr/share/doc/kde4/HTML/en/KRegExpEditor/altn.png
usr/share/doc/kde4/HTML/en/KRegExpEditor/altntool.png
usr/share/doc/kde4/HTML/en/KRegExpEditor/anychar.png
usr/share/doc/kde4/HTML/en/KRegExpEditor/anychartool.png
usr/share/doc/kde4/HTML/en/KRegExpEditor/begline.png
usr/share/doc/kde4/HTML/en/KRegExpEditor/boundarytools.png
usr/share/doc/kde4/HTML/en/KRegExpEditor/characters.png
usr/share/doc/kde4/HTML/en/KRegExpEditor/charactertool.png
usr/share/doc/kde4/HTML/en/KRegExpEditor/compound.png
usr/share/doc/kde4/HTML/en/KRegExpEditor/compoundtool.png
usr/share/doc/kde4/HTML/en/KRegExpEditor/endline.png
usr/share/doc/kde4/HTML/en/KRegExpEditor/linestartendtool.png
usr/share/doc/kde4/HTML/en/KRegExpEditor/lookaheadtools.png
usr/share/doc/kde4/HTML/en/KRegExpEditor/neglookahead.png
usr/share/doc/kde4/HTML/en/KRegExpEditor/nonwordboundary.png
usr/share/doc/kde4/HTML/en/KRegExpEditor/poslookahead.png
usr/share/doc/kde4/HTML/en/KRegExpEditor/repeat.png
usr/share/doc/kde4/HTML/en/KRegExpEditor/repeattool.png
usr/share/doc/kde4/HTML/en/KRegExpEditor/select.png
usr/share/doc/kde4/HTML/en/KRegExpEditor/theEditor.png
usr/share/doc/kde4/HTML/en/KRegExpEditor/texttool.png
usr/share/doc/kde4/HTML/en/KRegExpEditor/text.png
usr/share/doc/kde4/HTML/en/KRegExpEditor/wordboundary.png

usr/share/doc/kde4/HTML/en/ktimer/index.cache.bz2
usr/share/doc/kde4/HTML/en/ktimer/index.docbook

usr/share/doc/kde4/HTML/en/kwallet/index.cache.bz2
usr/share/doc/kde4/HTML/en/kwallet/index.docbook
usr/share/doc/kde4/HTML/en/kwallet/edit1.png
usr/share/doc/kde4/HTML/en/kwallet/edit2.png
usr/share/doc/kde4/HTML/en/kwallet/edit3.png
usr/share/doc/kde4/HTML/en/kwallet/kwalletmanager.png
usr/share/doc/kde4/HTML/en/kwallet/ox22-action-wallet_closed.png
usr/share/doc/kde4/HTML/en/kwallet/ox22-action-wallet_open.png
usr/share/doc/kde4/HTML/en/kwallet/password1.png
usr/share/doc/kde4/HTML/en/kwallet/password2.png

usr/share/doc/kde4/HTML/en/superkaramba/index.cache.bz2
usr/share/doc/kde4/HTML/en/superkaramba/index.docbook

